b2bportal/b2bportal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [

    path('', include(('core.urls', 'home'), namespace='home')),
    path('admin/', admin.site.urls),
]

b2bportal/core/urls.py
from core.UtilityView import *
from .views import *
from django.urls import path,re_path
from .booking import *
 
from django.contrib.auth.views import LogoutView
urlpatterns = [
path('',dashboard,name='home'),
path('home/',dashboard,name='dashboard'),
path('dashboard/',dashboard,name='dashboard'),
path('success/',success,name='success'),
path('clientreport/',clientreport,name="clientreport"),
path('invoice/',invoice,name="invoice"),
path('tracking/', tracking, name='tracking'),
#path('TrackShipment/<waybillno1>', tracking1, name='tracking-waybill'),

path('SuccessView/',SuccessView,name="SuccessView"),
path('add-to-favourite/',add_to_favourite,name="add-to-favourite"),
path('favouritebooking/',favouritebooking,name="favouritebooking"),
 
path('reschedulebooking/<int:id>',reschedulebooking,name="reschedulebooking"),
  
#path('printbooking/',PrintBooking,name="printbooking"), 
path('deletebooking/<int:id>',deletebooking,name="deletebooking"),
path('deleteUploadBooking/<int:id>',deleteUploadBooking,name="deleteUploadBooking"),
path('newconsignee/',newconsignee,name="newconsignee"),
path('Registeration/',Register,name="Register"),
path('Enquiries/',Enquiries,name="Enquiries"),
path('edd/', estimated_delivery, name='edd'),
path('profile/', basecompanyprofile, name='profile'),

path('get/ajax/validate/cities', checkCities, name="validate_checkCities"),
path('post/ajax/data/saveEDD', saveEDD, name="save_edd"),
path('getconsignee/<str:consigneeid>/', getconsignee, name='getconsignee'),

path('logoff/', LogoutView.as_view(next_page='/'), name='logoff'), 
path('premium-login/', b2blogin, name='b2blogin'),
#re_path(r"^(?:page-(?P<page_number>\d+)/)?$", booking, name="bookinglistview"),
#path('booking/', bookingHTMxTableView.as_view(),name='booking'),
path('create-pdf', pdf_report_create, name="create-pdf"),
path('alertnotification/<int:booking_id>/<int:alert_type>', alertnotification, name="alertnotification"), 

path('UploadBooking', UploadBooking, name="UploadBooking"),
#path('reset_password', reset_password, name="reset_password"),
path("password_reset/", password_reset_request, name="password_reset"),
path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='b2bportal/password/password_reset_done.html'), name='password_reset_done'),
path('reset/<uidb64>/<token>/', B2BPasswordResetConfirmView.as_view(template_name="b2bportal/password/password_reset_confirm.html"), name='password_reset_confirm'),
path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='b2bportal/password/password_reset_complete.html'), name='password_reset_complete'),  
path('printbooking/',PrintBooking,name="printbooking"), 

#autocomplete
path('country-autocomplete/',
        CountryAutocomplete.as_view(),
        name='country-autocomplete',
    ),

path('city-autocomplete/',
        CityAutocomplete.as_view(),
        name='city-autocomplete',
    ),

# new Urls
path('confirm-booking/<int:booking_id>/',ConfirmBooking,name="confirm-booking"),
path('booking/<int:booking_id>/',newbooking,name="booking"),
path('booking-view/',BookingView,name="booking-view"),
path('booking-list/',booking_list,name="booking-list"),
path('shipper-lookup/', shipper_lookup, name='shipper-lookup'),
path('reciver-address-lookup/', reciver_address_lookup, name='reciver-address-lookup'),
path('dimensions/', dimensions, name='dimensions'),
path('add-new-shipper/', add_new_shipper, name='add-new-shipper'),
path('getembedinfo', get_embed_info,name="/getembedinfo"),
path('Price_Estimator/', Price_Estimator, name='Price_Estimator'),
# path('LoadType/', LoadType, name='LoadType'),
]  

b2bportal/core/models.py
from email.policy import default
from itertools import count
import string
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager, UserManager
from django.core.validators import RegexValidator
from datetime import datetime
from django.forms import IntegerField
from django.utils.translation import gettext_lazy as _
from psycopg2 import IntegrityError
from tinymce.models import HTMLField
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
#from .EmailUtility import send_html_mail
from django_pgviews import view as pg
from datetime import date
from tinymce.models import HTMLField
from django.utils.timezone import now
# Create your models here.

BOOKING_STATUS = [
    ('Booked', 'Booked'),
    ('Courier-Informed', 'Courier-Informed'),
    ('Cancel-Booking', 'Cancel-Booking'),
    ('Scheduled', 'Scheduled'),
    ('Picked-Up','Picked-Up'),
    ('Miss-PickUp','Miss-PickUp'),
    ('Acknowledge','Acknowledge'),   
]
PAYMENT_METHOD = [
    ('Cash', 'Cash'),
    ('Credit-card', 'Credit-card'),
    ('Shipper-Account', 'Shipper-Account'),
    ('Other-Account-Type', 'Other-Account-Type'),
    
]

class NaqelUser(AbstractUser):
    objects = UserManager()
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message=_(
        "Enter a valid international mobile phone number starting with +(country code)"))
    mobile_phone = models.CharField(validators=[phone_regex], verbose_name=_(
        "Mobile phone"), max_length=20, unique=True, null=True)
    username = models.CharField(
        'username', max_length=50, unique=True, db_index=True)
        
    fullname = models.CharField(
        'fullname', max_length=191, null=True, blank=True)
    email = models.EmailField(max_length=191, unique=True)
    additional_information = models.CharField(verbose_name=_(
        "Additional information"), max_length=100, blank=True, null=True)
    created_date = models.DateTimeField(default=now, blank=True)
    firebaseuid = models.CharField(max_length=100, null=True, blank=True)
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    firebasedeviceid = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        ordering = ['username']

    def __str__(self):
        return f"{self.username}: {self.email}:{self.fullname} "

class status(models.Model):
    code=models.CharField(max_length=100, null=True, blank=True)
    name=models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return f"{self.code}: {self.name} "

class country(models.Model):
    code=models.CharField(max_length=100, null=True, blank=True)
    name=models.CharField(max_length=100, null=True, blank=True)
    info_Country_id = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.name} "

class city(models.Model):
    code=models.CharField(max_length=100, null=True, blank=True)
    name=models.CharField(max_length=100, null=True, blank=True)
    station = models.CharField(max_length=100, null=True, blank=True)
    country = models.ForeignKey(country, on_delete=models.CASCADE,null=True, blank=True)

    def __str__(self):
        return f"{self.name} "



class state(models.Model):
    code=models.CharField(max_length=100, null=True, blank=True)
    name=models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return f"{self.code}: {self.name} "

class podtype(models.Model):
    code=models.CharField(max_length=100, null=True, blank=True)
    name=models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return f"{self.code}: {self.name} "

class shipmenttype(models.Model):
    code=models.CharField(max_length=100, null=True, blank=True)
    name=models.CharField(max_length=100, null=True, blank=True)
    type=models.CharField(max_length=100, null=True, blank=True)
    shipment_id=models.IntegerField(null=True, blank=True)
    ServiceTypeID=models.IntegerField(null=True, blank=True)
    ServiceType=models.CharField(max_length=100, null=True, blank=True)
    ClientID=models.CharField(max_length=100, null=True, blank=True)
    infotrack_id = models.IntegerField(null=True, blank=True)    

    def __str__(self):
        return f"{self.name}"

class billingtype(models.Model): 
    code=models.CharField(max_length=100, null=True, blank=True)
    name=models.CharField(max_length=100, null=True, blank=True)
    type=models.CharField(max_length=100, null=True, blank=True)    

    def __str__(self):
        return f"{self.name}"        


class CompanyProfile(models.Model):
    company_name=models.CharField(max_length=100, null=True, blank=True)
    client_id = models.CharField(
        max_length=100, unique=True, null=True, blank=True)
    registration_number=models.CharField(max_length=100,null=True, blank=True)
    phone_number=models.CharField(max_length=100, null=True, blank=True)
    email_address=models.CharField(max_length=100, null=True, blank=True)
    country= models.ForeignKey("country",related_name="company_country", on_delete=models.SET_NULL,null=True, blank=True)
    city=models.ForeignKey("city",related_name="comapny_city", on_delete=models.SET_NULL,null=True, blank=True)
    state=models.ForeignKey("state",related_name="company_state", on_delete=models.SET_NULL,null=True, blank=True)
    post_code=models.IntegerField(null=True, blank=True)
    comapny_origin=models.ForeignKey("city",related_name="company_org_city", on_delete=models.SET_NULL,null=True, blank=True)
    location = models.CharField(max_length=100,null=True, blank=True)
    allowed_users=models.ManyToManyField("NaqelUser",null=True, blank=True)
    customer_type = models.CharField(max_length=100,null=True, blank=True)

    def __str__(self):
        return f"{self.company_name} " 
    

class address(models.Model):
    contact_person = models.CharField(max_length=100, null=True, blank=True)
    address1 = models.CharField(max_length=100, null=True, blank=True)
    address2 = models.CharField(
        max_length=100, null=True, blank=True)
    mobile_number1 = models.CharField(max_length=100, null=True, blank=True)
    mobile_number2 = models.CharField(max_length=100, null=True, blank=True)
    country = models.ForeignKey("country",related_name="address_country", on_delete=models.SET_NULL,null=True, blank=True)
    city = models.ForeignKey("city",related_name="address_city", on_delete=models.SET_NULL,null=True, blank=True)
    client = models.ForeignKey("client",related_name="shipper_client", on_delete=models.SET_NULL,null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lng = models.FloatField(null=True, blank=True)
    

    

    def __str__(self):
        return f"{self.address1} " 

#Added for New Booking Screen

class consignee(models.Model):
    company_name = models.ForeignKey("CompanyProfile",related_name="consignee_comapny_name", on_delete=models.SET_NULL,null=True, blank=True)
    contact_person=models.CharField(max_length=100, null=True, blank=True)
    contact_number =  models.CharField(max_length=100, null=True, blank=True)
    mobile_number =  models.CharField(max_length=100, null=True, blank=True)
    address=  models.CharField(max_length=191, null=True, blank=True) 
    country = models.ForeignKey("country",related_name="consignee_country", on_delete=models.SET_NULL,null=True, blank=True)
    city = models.ForeignKey("city",related_name="consignee_city", on_delete=models.SET_NULL,null=True, blank=True)
    pickup_point =  models.CharField(max_length=100, null=True, blank=True)
    shipping_instruction =  models.CharField(max_length=100, null=True, blank=True)
    account_number = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=70, blank=True, null=True)
    zip_code=models.IntegerField(null=True, blank=True)
    
    @classmethod
    def create(cls,request,company_name,contact_person,contact_number,mobile_number,address,country,city,pickup_point,email,zip_code):
        cons=cls(company_name,contact_person,contact_number,mobile_number,address,country,city,pickup_point,email,zip_code) 
        return cons
# class consignee(models.Model):
#     contact_person1 = models.ForeignKey("consignee",related_name="consignee_contact_person", on_delete=models.SET_NULL,null=True, blank=True)
#     contact_person = models.CharField(max_length=100, null=True, blank=True)
#     address1 = models.CharField(max_length=100, null=True, blank=True)
#     address2 = models.CharField(
#         max_length=100, null=True, blank=True)
#     mobile_number1 = models.CharField(max_length=100, null=True, blank=True)
#     mobile_number2 = models.CharField(max_length=100, null=True, blank=True)
#     email_id=models.CharField(max_length=100, null=True, blank=True)
#     country = models.ForeignKey("country",related_name="consignee_country", on_delete=models.SET_NULL,null=True, blank=True)
#     city = models.ForeignKey("city",related_name="consignee_city", on_delete=models.SET_NULL,null=True, blank=True)
#     client = models.ForeignKey("client",related_name="consignee_client", on_delete=models.SET_NULL,null=True, blank=True)
#     lat = models.FloatField(null=True, blank=True)
#     lng = models.FloatField(null=True, blank=True)
#     is_inactive= models.BooleanField(default=False)
    
#     def __str__(self):
#         return f"{self.contact_person} "
        
#     def __unicode__(self):
#         return self.contact_person        

# class Booking(models.Model):
#     reference = models.CharField(max_length=100, null=True, blank=True)
#     company_name = models.ForeignKey("CompanyProfile",related_name="booking_comapny_name", on_delete=models.SET_NULL,null=True, blank=True)

b2bportal/core/templates/b2bportal/password/change_password.html
{% extends "b2bportal/base_withoutmenu.html" %}
{% load static %}


{% block content %}
<br/>
<br/>
<div class="container mt-120">
	<div class="row m-3 justify-content-center divShadow">
		<div class="col-md-6 round mt-3">
			<form method="post">
				<br/>
				{% csrf_token %}
				{{ form }}
					<div align="center">
					<button class="btn trackbtn bg-danger text-white " style="width: 130px; font-size: 12px;"
							type="submit">
						Save  Changes
					</button>
				</div>
			</form>
		</div>
	</div>
</div>
<br/>
<br/>
{% endblock %}

b2bportal/core/templates/b2bportal/password/password_reset.html
{% extends "b2bportal/base_withoutmenu.html" %}
{% load static %}

 
{% block content %}
<br/>
<br/>
<style>
#Email {
    display: none;
  
}

#phone1 {
    display: none;
   
}

input[value="email"]:checked ~ #Email {
    display: block;
}

input[value="phone1"]:checked ~ #phone1 {
    display: block;
}
input[type=checkbox], input[type=radio] {
    box-sizing: border-box;
    padding: 0;
    visibility: hidden;
}
</style>

<link rel="stylesheet" href="{% static 'css/intlTelInput.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{% static 'js/intlTelInput.js' %}"></script>
 
<div class="container">
	<div class="row justify-content-center ">
		<div class="col-md-6 round mt-3 divShadow">
			<br/>
			<h3 align="center" class="text-white"><b>Forgot your password!</b></h3>
		
			<form  method="post" action="">
				<br/>
				{% csrf_token %}
				<input type="radio" name="c" value="email" checked="checked" >
				
				{% if error == None %}
				<br>
				{% else %}
				<div class="alert alert-danger">
					<h5>{{error}}</h5>
				</div>
				{% endif %}
				<br>
				<div id="Email">
					<i class="fa fa-envelope prefix text-white"></i>
					<label for="id_email" class="text-white">Email</label>
					{{ form.email }}
					
				</div>
				
				<div id="phone1">

					<i class="fa fa-phone prefix "></i>
					<label for="id_mobile_phone">Phone Number</label>
					{{ form.phone }}
					{% if form.phone.errors %}
                    <p class="text-danger"> {{form.phone.errors}} </p>
                    {%endif%}
				
				</div> 
				
				
					<div align="center">
					<button class="btn trackbtn bg-danger text-white " style="width: 130px; font-size: 12px;"
							type="submit">
						Submit 
					</button>
					<a href="/premium-login" class="btn btn-danger btn-rounded"><i class="fa fa-home"></i>
						Home</a>
				</div>
			</form> 
			<hr/>
		</div>
	</div>
</div>
<br/>
<br/>



<script>
var input = document.querySelector("#phone");
var iti =   window.intlTelInput(input,({
	 initialCountry: "auto",
geoIpLookup: function(success, failure) {
 $.get("https://ipinfo.io", function() {}, "jsonp").always(function(resp) {
   var countryCode = (resp && resp.country) ? resp.country : "us";
   success(countryCode);
 });
},
}));

 iti.promise.then(function() {
var countryData = iti.getSelectedCountryData();
console.log(countryData);
$('#phone').val("+"+countryData.dialCode);
});

$(document).ready(function() {
  $('.iti__flag-container').click(function() {
	var countryCode = $('.iti__selected-flag').attr('title');
	var countryCode = countryCode.replace(/[^0-9]/g,'')
	$('#phone').val("");
	$('#phone').val("+"+countryCode+""+ $('#phone').val());
 });
});
</script>
{% endblock %}

b2bportal/core/templates/b2bportal/password/password_reset_complete.html
{% extends "b2bportal/base_withoutmenu.html" %}
{% load static %}
 


{% block content %}

<br/>
<br/>

<div class="main-site">
	<div class="cmt-bgcolor-white box-shadow spacing-14 border-rad_10">
	<section class="pt-60 pb-65 res-991-pb-40 clearfix">
	<div class="container">

		<div class="row">
			<div class="col-lg-10 col-md-10 col-sm-12">
				<div class="cmt-bgcolor-grey  card-resultpages">
					<div class="mb-20">
						<strong><p class=" p-10 res-991-pr-0 Naqelbluecolor"> Your password has been set. You may go ahead and <a href="/premium-login">login</a> now.</p></strong>
					</div>
				</div>
			</div>
		</div>
	</div>
	</section>
</div>
</div>


{% endblock %}

b2bportal/core/templates/b2bportal/password/password_reset_confirm.html
{% extends "b2bportal/base_withoutmenu.html" %}
{% load static %}


{% block content %}
<div class="container mt-120">
	<div class="row m-3 justify-content-center ">
		<div class="col-md-6 round mt-3" style="-webkit-box-shadow: 12px 29px 81px 0px rgba(0,0,0,0.75);
    -moz-box-shadow: 12px 29px 81px 0px rgba(0,0,0,0.75);
    box-shadow: 12px 29px 81px 0px rgba(0,0,0,0.75);">
			{% if validlink %}
			<br/>
			<h3 align="center">Change Password</h3>
			<form action="" method="post">
				<div style="display:none">
					<input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
				</div>
				<div align="center" class="form-group">
					{{ form.new_password1.errors }}
					<label class="col-md-4 control-label ">New Password:</label>
					<div class="col-md-10">
						{{ form.new_password1 }}
					</div>
				</div>

				<div align="center" class="form-group">
					{{ form.new_password2.errors }}
					<label class="col-md-4 control-label">Confirm Password:</label>
					<div class="col-md-10">
						{{ form.new_password2 }}
					</div>
				</div>
				<div align="center">
					<button class="btn trackbtn bg-danger text-white " style="width: 130px; font-size: 12px;"
							type="submit">
						Change password
					</button>
				</div>
			</form>
			<br/>
			{% else %}
			<br>
			<div class="row">
				<div class="col-lg-10 col-md-10 col-sm-12">
					<div class="cmt-bgcolor-grey  card-resultpages">
						<div class="mb-20">
							<strong><p class=" p-10 res-991-pr-0 text-danger"> Password reset unsuccessful</p></strong>
							<strong><p class=" p-10 res-991-pr-0 Naqelbluecolor"> 	The password reset link was invalid, possibly because it has already been used.
								Please request a new password reset.</p></strong>
						</div>
					</div>
				</div>
			</div>
			{% endif %}
		</div>
	</div>
</div>

{% endblock %}

b2bportal/core/templates/b2bportal/password/password_reset_done.html
{% extends "b2bportal/base_withoutmenu.html" %}
{% load static %}
 
{% block content %}
<hr/>
<br/>
<br/>
<div class="container mt-120" style="min-height: 400px;">
	<div class="row m-3 justify-content-center divShadow ">

		<div class="col-md-8 round m-3 text-dark">

			<h5 class="Naqelbluecolor text-white">
				We've sent details to reset your password on your registered email.

				If you do not receive any details, please contact us or call us at: 920020505.
			</h5>
		<!-- 	<h5>
				If you don't receive an email, please make sure you've entered the address you registered with,
				and check your spam folder.
			</h5> -->
			<a href="/premium-login" class="btn btn-danger btn-rounded"><i class="fa fa-home"></i>
				Home</a>
		</div>
	</div>
</div>

{% endblock %}

b2bportal/core/templates/b2bportal/password/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} NAQEL Express Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
NAQEL Express IT Team
{% endautoescape %}

b2bportal/core/templates/b2bportal/password/password_reset_form.html
{% extends "b2bportal/base_withoutmenu.html" %}
{% load static %}
{% block title %}Forgot Your Password?{% endblock %}
{% block content %}

<hr/>
<br/>
<br/>
<div class="container mt-120">
	<div class="row justify-content-center">
		<div  class="col-md-4 round mt-3" style="-webkit-box-shadow: 12px 29px 81px 0px rgba(0,0,0,0.75);
    -moz-box-shadow: 12px 29px 81px 0px rgba(0,0,0,0.75);
    box-shadow: 12px 29px 81px 0px rgba(0,0,0,0.75);">
			<br/>
			<h3 align="center">Forgot your password?</h3>
			<p align="center">Enter your email address below</p>

			<form method="POST">
				{% csrf_token %}
				{{ form.as_p }}
				<div align="center">
					<button class="btn trackbtn bg-danger text-white " style="width: 130px; font-size: 12px;"
							type="submit">
						Send me Instructions!
					</button>
				</div>
			</form>
			<br/>
		</div>
	</div>
</div>
<hr/>
<br/>
<br/>
{% endblock %}