b2bportal/b2bportal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [

    path('', include(('core.urls', 'home'), namespace='home')),
    path('admin/', admin.site.urls),
]

b2bportal/core/urls.py
from core.UtilityView import *
from .views import *
from django.urls import path,re_path
from .booking import *
 
from django.contrib.auth.views import LogoutView
urlpatterns = [
path('',dashboard,name='home'),
path('home/',dashboard,name='dashboard'),
path('dashboard/',dashboard,name='dashboard'),
path('success/',success,name='success'),
path('clientreport/',clientreport,name="clientreport"),
path('invoice/',invoice,name="invoice"),
path('tracking/', tracking, name='tracking'),
#path('TrackShipment/<waybillno1>', tracking1, name='tracking-waybill'),

path('SuccessView/',SuccessView,name="SuccessView"),
path('add-to-favourite/',add_to_favourite,name="add-to-favourite"),
path('favouritebooking/',favouritebooking,name="favouritebooking"),
 
path('reschedulebooking/<int:id>',reschedulebooking,name="reschedulebooking"),
  
#path('printbooking/',PrintBooking,name="printbooking"), 
path('deletebooking/<int:id>',deletebooking,name="deletebooking"),
path('deleteUploadBooking/<int:id>',deleteUploadBooking,name="deleteUploadBooking"),
path('newconsignee/',newconsignee,name="newconsignee"),
path('Registeration/',Register,name="Register"),
path('Enquiries/',Enquiries,name="Enquiries"),
path('edd/', estimated_delivery, name='edd'),
path('profile/', basecompanyprofile, name='profile'),

path('get/ajax/validate/cities', checkCities, name="validate_checkCities"),
path('post/ajax/data/saveEDD', saveEDD, name="save_edd"),
path('getconsignee/<str:consigneeid>/', getconsignee, name='getconsignee'),

path('logoff/', LogoutView.as_view(next_page='/'), name='logoff'), 
path('premium-login/', b2blogin, name='b2blogin'),
#re_path(r"^(?:page-(?P<page_number>\d+)/)?$", booking, name="bookinglistview"),
#path('booking/', bookingHTMxTableView.as_view(),name='booking'),
path('create-pdf', pdf_report_create, name="create-pdf"),
path('alertnotification/<int:booking_id>/<int:alert_type>', alertnotification, name="alertnotification"), 

path('UploadBooking', UploadBooking, name="UploadBooking"),
#path('reset_password', reset_password, name="reset_password"),
path("password_reset/", password_reset_request, name="password_reset"),
path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='b2bportal/password/password_reset_done.html'), name='password_reset_done'),
path('reset/<uidb64>/<token>/', B2BPasswordResetConfirmView.as_view(template_name="b2bportal/password/password_reset_confirm.html"), name='password_reset_confirm'),
path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='b2bportal/password/password_reset_complete.html'), name='password_reset_complete'),  
path('printbooking/',PrintBooking,name="printbooking"), 

#autocomplete
path('country-autocomplete/',
        CountryAutocomplete.as_view(),
        name='country-autocomplete',
    ),

path('city-autocomplete/',
        CityAutocomplete.as_view(),
        name='city-autocomplete',
    ),

# new Urls
path('confirm-booking/<int:booking_id>/',ConfirmBooking,name="confirm-booking"),
path('booking/<int:booking_id>/',newbooking,name="booking"),
path('booking-view/',BookingView,name="booking-view"),
path('booking-list/',booking_list,name="booking-list"),
path('shipper-lookup/', shipper_lookup, name='shipper-lookup'),
path('reciver-address-lookup/', reciver_address_lookup, name='reciver-address-lookup'),
path('dimensions/', dimensions, name='dimensions'),
path('add-new-shipper/', add_new_shipper, name='add-new-shipper'),
path('getembedinfo', get_embed_info,name="/getembedinfo"),
path('Price_Estimator/', Price_Estimator, name='Price_Estimator'),
# path('LoadType/', LoadType, name='LoadType'),
]  

b2bportal/core/views.py
#Email pass

from email import message
from urllib.request import Request
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetConfirmView,PasswordContextMixin
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.contrib import messages #import messages
from django.utils.html import format_html
#Email
from .booking import CustomerWaybill,ShipmentBookingForm
from dataclasses import field, fields
from email.policy import default
from msilib.schema import Class
#from msilib.schema import tables
from multiprocessing import context
from telnetlib import STATUS
from types import CodeType
from urllib import response
from django.forms import modelformset_factory
from django.http import HttpResponse
from django.shortcuts import render
from requests import request
from django.template.loader import get_template
from xhtml2pdf import pisa

#pdf generate
import reportlab
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas

#pdf generate
from .forms import *
from django.template.response import TemplateResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
import logging
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import AbstractUser, BaseUserManager, UserManager
 
import django_tables2 as tables
from django.core.management import call_command
from django.views.decorators.http import require_http_methods, require_GET
# Create your views here.
from decimal import Decimal
from django.db.models import Q
import django_filters
from django_tables2 import SingleTableMixin, TemplateColumn
from django_filters.views import FilterView
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import views as auth_views
from django.db.models import Prefetch
from django.db.models import Count
from django.db import transaction
from sequences import Sequence
from django.db.models.signals import post_save
from django.dispatch import receiver

WaybillNumber = Sequence("waybill_numbers",initial_value=235255555)
document_no = Sequence("doc_numbers",initial_value=1000)
#for tracking : import below
from ast import Or, arg
from django.shortcuts import render
from datetime import datetime
import re
import requests
from requests.api import patch
from .forms import  *
import time as tt
#tracking end
from django.contrib.staticfiles import finders
from django.conf import settings
import os
from core.EmailUtility import send_html_mail
from django.http import HttpResponseRedirect
from tablib import Dataset

from .config import BaseConfig as CC
import json
from .services import pbiembedservice as PbiEmbedService
from django.http import HttpResponse
# import pywhatkit as kit

import mimetypes

api_host="http://212.107.118.74:81/b2b/"
# from django.contrib.sites.shortcuts import get_current_site
 
 
def get_embed_info(request):
    try:

        B2B="21c9a08b-2d55-46af-97a7-19bd5977092b"
        B2C="3da14145-f206-4ed0-b254-8a05bc0b6145"
        POWERBI_ID="21c9a08b-2d55-46af-97a7-19bd5977092b"
        company=GetCurrentCompany(request)
        cust_type=company.customer_type
        if cust_type == 'B2B':
            POWERBI_ID=B2B
        else:
            POWERBI_ID=B2C
            
        pb= PbiEmbedService.PbiEmbedService()
        embed_info = pb.get_embed_params_for_single_report(CC.WORKSPACE_ID, POWERBI_ID)
        return HttpResponse(embed_info, content_type='application/json')
    except Exception as ex:
        return json.dumps({'errorMsg': str(ex)}), 500

 
def Price_Estimator(request):
    print("Rashmi")
    if request.htmx:
            base_template="b2bportal/_partial.html"
    else:
        base_template="b2bportal/base.html"
        
    url ="https://infotrack.naqelexpress.com/NaqelAPIServices/NaqelAPI/9.0/XMLShippingService.asmx?op=GetRate"
    print(url)
    payload = """<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:GetRate>
         <!--Optional:-->
         <tem:ClientInfo>
            <!--Optional:-->
            <tem:ClientAddress>
               <!--Optional:-->
               <tem:PhoneNumber>0532155580</tem:PhoneNumber>
               <!--Optional:-->
               <tem:POBox>Box</tem:POBox>
               <!--Optional:-->
               <tem:ZipCode>1002</tem:ZipCode>
               <!--Optional:-->
               <tem:Fax>?</tem:Fax>
               <!--Optional:-->
               <tem:FirstAddress>?</tem:FirstAddress>
               <!--Optional:-->
               <tem:Location>?</tem:Location>
               <!--Optional:-->
               <tem:CountryCode>1</tem:CountryCode>
               <!--Optional:-->
               <tem:CityCode>1</tem:CityCode>
            </tem:ClientAddress>
            <!--Optional:-->
            <tem:ClientContact>
               <!--Optional:-->
               <tem:Name>?</tem:Name>
               <!--Optional:-->
               <tem:Email>?</tem:Email>
               <!--Optional:-->
               <tem:PhoneNumber>?</tem:PhoneNumber>
               <!--Optional:-->
               <tem:MobileNo>?</tem:MobileNo>
            </tem:ClientContact>
            <tem:ClientID>9020077</tem:ClientID>
            <!--Optional:-->
            <tem:Password>test1234</tem:Password>
            <!--Optional:-->
            <tem:Version>9.0</tem:Version>
         </tem:ClientInfo>
         <tem:Weight>5</tem:Weight>
         <tem:LoadTypeID>39</tem:LoadTypeID>
         <tem:FromDate>2022-10-26</tem:FromDate>
         <!--Optional:-->
         <tem:Origin>DMM</tem:Origin>
         <!--Optional:-->
         <tem:Destination>RUH</tem:Destination>
      </tem:GetRate>
   </soapenv:Body>
</soapenv:Envelope>
"""
    
    headers = {
        'Content-Type': 'text/xml; charset=utf-8'
    }
    response = requests.request("POST", url, headers=headers, data=payload)  
    records=response.content
    print(records)
     
    form=RateCalForm(request.POST)
    context={
         'form':form,
         'base_template':base_template
    }
    return render(request, 'b2bportal/Price_Estimator.html',context =context)
 
def GetCurrentCompany(request):
    company=None
    for comp in CompanyProfile.objects.all():
        data = comp.allowed_users.all().filter(id=request.user.id)
        if data:
            company = comp
            break
    return company
  

def success(request):
   showsummary=Booking.objects.all()
   context={
        'showsummary':showsummary
   }
   return render(request, 'b2bportal/success.html',context)
 


def pdf_report_create(request):
    showsummary=Booking.objects.all()
    template_path = 'b2bportal/pdfreport.html'
    context = {
        'showsummary':showsummary
    }
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)
    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funny view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    showsummary=Booking.objects.all()
    return response    

    
@login_required(login_url="/premium-login")
def dashboard(request):   
    context={}
    data=[]
    company=GetCurrentCompany(request)
    # ClientID=company.client_id
    ClientID=9019614
    service_list=StandardCode.objects.filter(CodeType='ServiceType')
    product_list=StandardCode.objects.filter(CodeType='ProductType')
    Region_list=StandardCode.objects.filter(CodeType='RegionType')
    city_list=city.objects.filter(code='CityCode')
    
    context={
        "standardcode":service_list, 
        "productCode":product_list,
        "RegionCode":Region_list,                                                           
        "CityCode":city_list,
    }
    if request.htmx:
        base_template="b2bportal/_partial.html"
    else:
        base_template="b2bportal/base.html"
 
    if "ServiceTypeID" in request.GET:
        request.session["ServiceTypeID"]=request.GET["ServiceTypeID"]
    if "ProductTypeID" in request.GET:
        request.session["ProductTypeID"]=request.GET["ProductTypeID"]

    if "RegionID" in request.GET:
        request.session["RegionID"]=request.GET["RegionID"]        
    
    ProductTypeID=request.session.get("ProductTypeID",7)
    ServiceTypeID=request.session.get("ServiceTypeID",2)
    RegionID=request.session.get("RegionID",3)
    CityID=3

 
    if request.method == 'POST':
        print('post')
        form = DashboardForm(request.POST)
         
        from_date = request.POST.get('from_date')
        to_date = request.POST.get('to_date')
        
        request.session["from_date"]=str(from_date)
        request.session["to_date"]=str(to_date)
 
 
        data=None
        context={}
        form = DashboardForm(
            initial={"from_date":from_date,"to_date":to_date}
        )
        
        context["base_template"]=base_template
       
        return render(request, 'b2bportal/dashboard.html',context=context)
     
    else:
        print('get')
        

        
        
        context["base_template"]=base_template
        return render(request, 'b2bportal/dashboard.html', context=context)
class BookingHTMxTable(tables.Table):

b2bportal/core/templates/b2bportal/Registeration_submission.html
{% extends "Shared/base.html" %}
{% load static %}
{% block content %}
<style>
.btn-primary {
	background-color: #06205c !important;
	padding: 4.5px 20px!important;
	float: right;
  }
</style>
<div class="main-site">
	<div class="cmt-bgcolor-white box-shadow spacing-14 border-rad_10">
	<section class="pt-60 pb-65 res-991-pb-40 clearfix">
	<div class="container">

		<div class="row">
			<div class="col-lg-10 col-md-10 col-sm-12">
				<div class="cmt-bgcolor-grey  card-resultpages">
					<div class="mb-20">
						<strong><p class=" p-10 res-991-pr-0 Naqelbluecolor">{{message}}</p></strong>
					</div>
					<!--featured-icon-box-->
					<div class="featured-icon-box icon-align-before-content  icon-ver_align-top style11">
						<div class="featured-content">
							<div class="featured-title">
								<a href="{{redirect}}" type="button" class="btn btn-primary"> OK</button>
									<i
									class="fa fa-angle-double-left"></i> {{linktext}} </a>
							</div>
						</div>
					</div><!-- featured-icon-box end-->
				</div>
			</div>
		</div>
	</div>
	</section>
</div>
</div>
{% endblock %}

b2bportal/core/templates/b2bportal/booking.html
{% extends base_template %}
{% load static %}

{% load render_table from django_tables2 %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}

<link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
 
<a class="right-side naqel-bg-color btn mt-0" href="{% url 'home:booking' 0 %}">
  <span class="text-white" >New booking</span>
</a>

<div class="home-content">
  <div class="row">
    <div class="col-lg-3 col-md-1 card w-350 h-170 ">
      <div class="row g-0">
        <div class="col-md-4">
          <div><i class='bx bx-loader naqel-text-color'></i></div>
        </div>
        <div class="col-md-8">
          <div>
            <h5 class="text-secondary"><b>Under Process</b></h5>
            <div class="number"><b>
                <h1 class="naqel-text-color">&nbsp;&nbsp;&nbsp;&nbsp;{{under_process}}
              </b></h1>
            </div>
            <p class="card-text"><small class="text-muted"></small></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-1 card  w-350 h-170">
      <div class="row g-0">
        <div class="col-md-4">
          <div><i class='bx bxs-check-circle box-3 naqel-text-color'></i></div>
        </div>
        <div class="col-md-8">
          <div>
            <h5 class="text-secondary"><b>Submitted</b></h5>
            <div class="number"><b>
                <h1 class="naqel-text-color">&nbsp;&nbsp;&nbsp;{{submitted}}
              </b></h1>
            </div>
            <p class="card-text"><small class="text-muted"></small></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-1 card w-350 h-170">
      <div class="row g-0">
        <div class="col-md-4">
          <div><i class='bx bxs-calendar-event naqel-text-color'></i></div>
        </div>
        <div class="col-md-8">
          <div>
            <h5 class="text-secondary">&nbsp;&nbsp;<b>Draft</b></h5>
            <div class="number"><b>
                <h1 class="naqel-text-color">&nbsp;{{un_submitted}}
              </b></h1>
            </div>
            <p class="card-text"><small class="text-muted"></small></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-1 card w-350 h-170">
      <div class="row g-0" >
        <div class="col-md-4">
          <div><i class='bx bxs-star bx-2x icon-8x naqel-text-color'></i></div>
        </div>
        <div class="col-md-8">
          <div>
            <h5 class="naqel-bg-blue"><a class="text-primary-blue" hx-get="/favouritebooking/" hx-target="#dialog"
                href="/favouritebooking/"><b><u>Favourites</u></b></a></h5>
            <div class="number"><b>
                <h1 class="naqel-text-color">&nbsp;&nbsp;&nbsp;{{favourite}}
              </b></h1>
            </div>
            <p class="card-text"><small class="text-muted"></small></p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row p-2">  
    <div class="col-lg-7">
      <form hx-get="{% url 'home:booking' %}"  hx-target="div.table-container" 
      hx-swap="innerHTML" 
      hx-indicator=".progress" 
      class="form-inline">
      
      <div class="row p-2">
          <div class="col-lg-4">
            <div class="input-group">
              <div class="input-group-prepend mr-2 text-naqel">
                <label for="start"><b>From Date</b></label>
              </div>
              {{filter.form.start_date|as_crispy_field }}
              
                 <!-- {{form.fromdate}}  -->
            </div>
          </div>
          
          <div class="col-lg-4">
            <div class="input-group">
              <div class="input-group-prepend mr-2 text-naqel">
                <label for="start"><b>To Date</b></label>
              </div>
              {{filter.form.end_date|as_crispy_field }}
              
            </div>
          </div>
          <div class="col-lg-4">
            <div class="input-group ">
              <div class="input-group-prepend mr-2">
                <!-- <i class="fa fa-sliders" aria-hidden="true"></i> -->
              </div>
              {{ filter.form.query|as_crispy_field}}
              
  
            </div>
          </div>
          <div class="col-lg-4">
            <div class="input-group ">
              <div class="input-group-prepend mr-2">
                <!-- <i class="fa fa-sliders" aria-hidden="true"></i> -->
              </div>
              <!-- <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-search"></span> Search
              </button> -->
            </div>
          </div>
     </div>
    </div>
    <div class="col-lg-4">
      <div class="input-group">
     
            <button type="submit" class="btn btn-primary ml-5 text-white" style="margin-right: 90px;" href="#"  data-toggle="tooltip" data-placement="top" title="Search">
              <span class="glyphicon glyphicon-search"></span><i class="fa fa-search fa-2x"></i>
            </button>
      </form>
        
           
       
        
        
     
        
        </div>
      </div>
  </div>
     

  
  <!-- <h>Product table</h1> -->
  
  <form action="/printbooking/" method="post"  name="myform">
            {% csrf_token %}              
      <div class="btn btn-primary text-white">
          
          <a type="button" id="dropdownMenuButton" formtarget="_blank" class="text-white dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="fa fa-print fa-2x"></i>    
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <button type="submit" name="print-sticker-label" formtarget="_blank"  class="dropdown-item naqel-text-color text-bold-front" href="#" onclick="return fnSticker();">Naqel Label</button>
            <button type="submit" name="print-sticker-A5"  formtarget="_blank" class="dropdown-item naqel-text-color text-bold-front" href="#" onclick="return fnSticker();">Label Sticker</button>
            <button type="submit" name="print-sticker-A4" formtarget="_blank" class="dropdown-item naqel-text-color text-bold-front" href="#" onclick="return fnSticker();">A4 Waybill</button>
          </div>
        </div>

        <a class="btn btn-primary text-white" data-toggle="tooltip" data-placement="top" title="Upload and Generate Waybill" href="#" onclick="onSubmitupload();">
          <i class="fa fa-upload fa-2x"></i>
        </a>
        <a  class="btn btn-primary text-white" data-toggle="tooltip" data-placement="top" title="Refresh"  href="{{ request.get_full_path }}">
        <i class='fa fa-refresh fa-2x'></i></a>
 
    {# The actual table #}
  
    {% render_table table %}
  
  </form>
  
    {# include "b2bportal/bookinghtmx.html" #}
  
   
  
  </div>
 
<script>
   
  function   onSubmitupload() 
    {
      window.location.href = '/UploadBooking';
    }

    function   daterange()
    {
      window.location.href = '/bookingSearch/';
    }
  
</script>
<style>
.table {
    width: 100%;
    margin-bottom: 1rem;
    color: #06205C!important;
}

.pagination .page-item.active>.page-link, .pagination .page-item.active>.page-link:focus, .pagination .page-item.active>.page-link:hover {
    background-color: #06205C!important;
    border-color: #51cbce;
    color: #FFFFFF;
}

  input[type=text], input[type=email], input[type=password], input[type=number], select, select2, textarea {
    width: 300px !important;
}
  .text-primary-blue{
   color: blue;

  }
   
  .card {
    border-radius: 4px !important;
    margin-bottom: 10px !important;
    position: relative;
    border: 12px solid rgba(0, 0, 0, .125);

  }

  /* .bg-text-green{
      color: green;
    } */


  .table>thead>tr>th {
    font-size: 15px;
    font-weight: 700;
    padding-bottom: 0;
    text-transform:none;
    border: 0;
    border : 5px solid white!important;
  }
 
  .row {
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    margin-right: -15px;
    margin-left: -15px;
    
  }

  .row-middle {
    background-color: red;
  }

  .table {
    width: 100%;
    background-color: white;
    margin-top: -1.5rem;
    
  }

  h5 {
    margin-top: 0px;
    margin-bottom: 25px;
    margin-left: 0px;
    margin-right: 0px;
  }

  .text-naqel {
    color: #06205C;
  }
  .text-naqel-greenyellow {
    color: #445c06;
  }
  .text-naqel-violet {
    color: #e337b2;
  }
  .bg-naqel-gray1 {
    background-color: #486af300;
  }
  .table>thead>tr>th, .table>tbody>tr>th, .table>tfoot>tr>th, .table>thead>tr>td, .table>tbody>tr>td, .table>tfoot>tr>td {
    padding: 0px 12px;
    vertical-align: middle;
}
h1, .h1 {
    font-size: 2.5em!important;
    line-height: 1.15!important;
    margin-bottom: 30px!important;
}

.btn:hover {
  background-color:firebrick!important;

}
/* button, input, optgroup, select, textarea {
    margin: 15px;
} */
</style>
 
{% endblock %}


{% block script%}
<script>

  function fnSticker()
  {
    var chebox = document.getElementsByName('selectaction');
    var options = document.getElementsByTagName('input');

    isChecked = false;
    for (var i = 0; i < options.length; i++) 
    {
      if (options[i].checked) 
      {
            isChecked = true;
      }
    }
    
    if(isChecked == false)
    {
      alert('Please select at least one waybill.')
    }

    return isChecked;
  }

  $('.reload').on("click",function(){
      alert("hi");
       location.reload();      
  });
  
  function confirmme(id)
  {
      if (confirm('Aye You sure to delete selected item?'+id))
      {
         htmx.ajax('GET', "/deletebooking/"+id, {target:'#dialog'})
         
      }
      else
      {
         event.stopPropagation(); event.preventDefault();
      }
      
  }
</script>

{% endblock %}

b2bportal/core/templates/b2bportal/booking_table_partial.html
{# booking_table_partial.html #}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}
 
{% render_table table %}

b2bportal/core/templates/b2bportal/bookinghtmx.html
{% load render_table from django_tables2 %}
<!--Include id="tableContainer" in enclosing container -->
<script>
    $('.reload').on("click",function(){
            location.reload();      
    });
    
    function confirmme(id)
    {
        if (confirm('Aye You sure to delete selected item?'+id))
        {
           htmx.ajax('GET', "/deletebooking/"+id, {target:'#dialog'})
           event.stopPropagation(); event.preventDefault();
        }
        else
        {
           event.stopPropagation(); event.preventDefault();
        }
        //hx-get="{% url 'home:deletebooking' record.booking_no.pk %}" hx-confirm="Are you sure you want to delete this customer?" hx-target="#dialog"
    }
</script>
<div id="tableContainer" class="overflow-x-auto max-w-5xl">
    <p class="font-semibold text-xs px-2 text-gray-600">Showing page {{ table.page.number }} of {{ table.paginator.num_pages }}</p>
    {% render_table table "/b2bportal/common/django_tables2.html" %}

</div>

    

b2bportal/core/templates/b2bportal/consigneehtmx.html
{{ formset.management_form }}
{% for form in formset %}
<div>
    <h5 class="modal-title naqel-bg-color text-white pl-1" id="exampleModalLabel">Consignee</h5>
</div>
    {{ form }}
{% endfor %}





<div class="form-group">
<!--<div class="row naqel-text-color">
    <div class="col-lg-5 col-md-1 pl-4">
        <div class="form-group ">
            <input type="text" class="form-control" id="consignee_name_id" placeholder="Address1">
        </div>
        <div class="form-group">
            <div>
                <input type="text" class="form-control" id="address1_id" placeholder="Address1">
            </div>
        </div>
        <div class="form-group">
            <div>
                <input type="text" class="form-control" id="address2_id" placeholder="Address2">
            </div>
        </div>

    </div>
    <div class="col-lg-2 col-md-1 pl-4">
        

    </div>
    <div class="col-lg-5 col-md-1 pl-4">
        <div class="form-group">
            <div>
                <input type="text" class="form-control" id="country_id" placeholder="City">
            </div>
        </div>
        <div class="form-group">
            <div>
                <input type="text" class="form-control" id="city_id" placeholder="Country">
            </div>
        </div>
        <div class="form-group">
            <div>
                <input type="text" class="form-control" id="phone_number_id" placeholder="Mobile">
            </div>
        </div>
    </div>
</div> -->